const $=id=>document.getElementById(id),content=$('content'),search=$('search'),summary=$('summary');let tracks=[],view='albums',query='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function match(t){const s=`${t.title} ${t.artist} ${t.album} ${t.albumArtist} ${(t.genres||[]).join(' ')}`.toLowerCase();return s.includes(query.toLowerCase())}
function save(t,patch){return window.wavedeck.savePortableMusicTrack({...t,...patch}).then(load)}
function controls(t){const box=document.createElement('div');box.className='stars';for(let n=1;n<=10;n++){const b=document.createElement('button');b.className=`star ${(t.rating||0)>=n?'on':''}`;b.textContent='★';b.title=`Rate ${n} of 10`;b.onclick=()=>save(t,{rating:n===t.rating?0:n});box.append(b)}return box}
function editTrack(t){const form=document.createElement('div');form.className='editor';form.innerHTML=`<div class="title">Edit song details</div><label>Title <input value="${esc(t.title)}"></label><label>Artist <input value="${esc(t.artist)}"></label><label>Album <input value="${esc(t.album)}"></label><label>Album Artist <input value="${esc(t.albumArtist)}"></label><label>Year <input value="${esc(t.year||'')}"></label><label>Genre <input value="${esc((t.genres||[]).join(', '))}"></label><label>Track <input value="${esc(t.track||'')}"></label><label>Disc <input value="${esc(t.disc||'')}"></label><button>Save details</button> <button type="button">Cancel</button>`;const inputs=[...form.querySelectorAll('input')];form.querySelector('button').onclick=()=>save(t,{title:inputs[0].value,artist:inputs[1].value,album:inputs[2].value,albumArtist:inputs[3].value,year:inputs[4].value,genres:inputs[5].value.split(',').map(v=>v.trim()).filter(Boolean),track:inputs[6].value,disc:inputs[7].value});form.querySelectorAll('button')[1].onclick=render;content.replaceChildren(form)}
function trackRow(t){const row=document.createElement('div');row.className=`track ${t.doNotPlay?'dnp':''}`;row.innerHTML=`<span class="small">${String(t.track||'—').padStart(2,'0')}</span><span><b>${esc(t.title)}</b><span class="meta"> ${esc(t.artist||'Unknown artist')}</span></span>`;row.children[1].onclick=()=>editTrack(t);const ban=document.createElement('button');ban.className=`ban ${t.doNotPlay?'on':''}`;ban.textContent='⊘';ban.title='Do Not Play';ban.onclick=()=>save(t,{doNotPlay:!t.doNotPlay});const heart=document.createElement('button');heart.className=`heart ${t.favorite?'on':''}`;heart.textContent=t.favorite?'♥':'♡';heart.title='Favorite';heart.onclick=()=>save(t,{favorite:!t.favorite});row.append(ban,controls(t),heart);return row}
function artistEditor(artist){const all=tracks.filter(t=>t.artist===artist);const related=[...new Set(all.flatMap(t=>t.manualRelatedArtists||[]))];const wrap=document.createElement('div');wrap.className='editor';wrap.innerHTML=`<b>${esc(artist)}</b><div class="related">Your related artists (Last.fm suggestions remain separate):</div><input value="${esc(related.join(', '))}" aria-label="Related artists"><button>Save relationships</button>`;wrap.querySelector('button').onclick=async()=>{const values=wrap.querySelector('input').value.split(',').map(v=>v.trim()).filter(Boolean);await window.wavedeck.saveArtistRelationships(artist,values);load()};return wrap}
function album(name,artist,items){const card=document.createElement('div');card.className='card';card.innerHTML=`<div class="title">${esc(name||'Loose Tracks')}</div><div class="meta">${esc(artist||'Unknown Artist')} · ${items.length} songs</div>`;card.onclick=()=>{content.replaceChildren(artistEditor(items[0].artist),Object.assign(document.createElement('div'),{className:'album'}));const head=content.querySelector('.album');head.append(Object.assign(document.createElement('div'),{className:'album-head',innerHTML:`<div><div class="title">${esc(name||'Loose Tracks')}</div><div class="meta">${esc(artist||'Unknown Artist')}</div></div><button>Back to Albums</button>`}));head.querySelector('button').onclick=render;const rows=document.createElement('div');rows.className='tracks';items.sort((a,b)=>(a.disc-b.disc)||(a.track-b.track)||a.title.localeCompare(b.title)).forEach(t=>rows.append(trackRow(t)));head.append(rows)};return card}
function render(){const shown=tracks.filter(match);content.replaceChildren();if(view==='artists'){const artists=[...new Set(shown.map(t=>t.artist||'Unknown Artist'))].sort();const grid=document.createElement('div');grid.className='grid';artists.forEach(a=>{const item=document.createElement('div');item.className='artist';item.innerHTML=`<div class="title">${esc(a)}</div><div class="meta">${shown.filter(t=>(t.artist||'Unknown Artist')===a).length} songs</div>`;item.onclick=()=>{query=a;search.value=a;view='albums';render()};grid.append(item)});content.append(grid);return}let filtered=shown;if(view==='needs')filtered=shown.filter(t=>!t.album||!t.artist||!(t.genres||[]).length);if(view==='genres'){const grid=document.createElement('div');grid.className='grid';[...new Set(shown.flatMap(t=>t.genres||[]))].sort().forEach(g=>{const c=document.createElement('div');c.className='card';c.textContent=g;c.onclick=()=>{query=g;search.value=g;view='albums';render()};grid.append(c)});content.append(grid);return}const groups=new Map;filtered.forEach(t=>{const k=`${t.albumArtist||t.artist}\n${t.album}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(t)});const grid=document.createElement('div');grid.className='grid';[...groups].sort((a,b)=>a[0].localeCompare(b[0])).forEach(([key,items])=>{const [artist,name]=key.split('\n');grid.append(album(name,artist,items))});content.append(grid)}
async function load(){tracks=await window.wavedeck.getPortableMusicLibrary();summary.textContent=`${tracks.length.toLocaleString()} songs · ${new Set(tracks.map(t=>t.album||t.title)).size.toLocaleString()} albums · ${new Set(tracks.map(t=>t.artist)).size.toLocaleString()} artists`;render()}
search.oninput=()=>{query=search.value;render()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});load().catch(e=>{summary.textContent=e.message});
